### ISSUE TITLE
unknown exception: ImageNotFound(HTTPError('404 Client Error: Not Found for url: http+docker://localhost/v1.35/containers/create?name=encoder'))

### ISSUE THREAD

**Issue by kingqiuol** [jina-ai/examples#115]
Traceback (most recent call last):
  File "/home/jinqiu/anaconda3/envs/jina/lib/python3.7/site-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/home/jinqiu/anaconda3/envs/jina/lib/python3.7/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.35/containers/create?name=encoder

Traceback (most recent call last):
  File "/home/jinqiu/anaconda3/envs/jina/lib/python3.7/site-packages/jina/peapods/pea.py", line 330, in run
    self.post_init()
  File "/home/jinqiu/anaconda3/envs/jina/lib/python3.7/site-packages/jina/peapods/container.py", line 70, in post_init
    entrypoint=self.args.entrypoint,
  File "/home/jinqiu/anaconda3/envs/jina/lib/python3.7/site-packages/docker/models/containers.py", line 807, in run
    detach=detach, **kwargs)
  File "/home/jinqiu/anaconda3/envs/jina/lib/python3.7/site-packages/docker/models/containers.py", line 861, in create
    resp = self.client.api.create_container(**create_kwargs)
  File "/home/jinqiu/anaconda3/envs/jina/lib/python3.7/site-packages/docker/api/container.py", line 430, in create_container
    return self.create_container_from_config(config, name)
  File "/home/jinqiu/anaconda3/envs/jina/lib/python3.7/site-packages/docker/api/container.py", line 441, in create_container_from_config
    return self._result(res, True)
  File "/home/jinqiu/anaconda3/envs/jina/lib/python3.7/site-packages/docker/api/client.py", line 267, in _result
    self._raise_for_status(response)
  File "/home/jinqiu/anaconda3/envs/jina/lib/python3.7/site-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/home/jinqiu/anaconda3/envs/jina/lib/python3.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.ImageNotFound: 404 Client Error: Not Found ("No such image: jinaai/hub.executors.encoders.image.torchvision-mobilenet_v2:latest")

**Comment by nan-wang** [comment]
hi, there. Would you please try `docker pull jinaai/hub.executors.encoders.image.torchvision-mobilenet_v2:latest`? Downloading the image might take too much time in some cases.
