### ISSUE TITLE
Error querying southpark-search tutorial

### ISSUE THREAD

**Issue by denysthegitmenace** [jina-ai/examples#173]
I followed the southpark-search tutorial.

When executing a search I get the following error:

```
(.venv) ➜  southpark-search python app.py -t query

           JINA@35805[E]:Since v0.3.6 jina uses uvloop to manage events and sockets, it often yields 20% speedupyou did not install uvloop. Try "pip install uvloop"
           JINA@35805[E]:Since v0.3.6 jina uses uvloop to manage events and sockets, it often yields 20% speedupyou did not install uvloop. Try "pip install uvloop"
           JINA@35805[E]:Since v0.3.6 jina uses uvloop to manage events and sockets, it often yields 20% speedupyou did not install uvloop. Try "pip install uvloop"
           JINA@35805[W]:parser Flow can not recognize the following args: ['--read-only', '--port-expose', '45678'], they are ignored. if you are using them from a global args (e.g. Flow), then please ignore this message
           JINA@35805[W]:parser FlowPod can not recognize the following args: ['--reducing-uses', '_merge_all'], they are ignored. if you are using them from a global args (e.g. Flow), then please ignore this message
           Flow@35805[S]:successfully built Flow from a yaml config
       splittor@35808[I]:post initiating, this may take some time...
       splittor@35808[I]:post initiating, this may take some time takes 0.001 secs
       splittor@35808[S]:successfully built Sentencizer from a yaml config
       splittor@35808[I]:setting up sockets...
       splittor@35808[I]:input tcp://0.0.0.0:52523 (PULL_BIND) 	 output tcp://0.0.0.0:52527 (PUSH_CONNECT)	 control over tcp://0.0.0.0:52525 (PAIR_BIND)
           JINA@35808[E]:Since v0.3.6 jina uses uvloop to manage events and sockets, it often yields 20% speedupyou did not install uvloop. Try "pip install uvloop"
       splittor@35808[S]:ready and listening
        encoder@35809[I]:post initiating, this may take some time...
        encoder@35809[I]:post initiating, this may take some time takes 2.166 secs
        encoder@35809[S]:successfully built TransformerTorchEncoder from a yaml config
        encoder@35809[I]:setting up sockets...
        encoder@35809[I]:input tcp://0.0.0.0:52527 (PULL_BIND) 	 output tcp://0.0.0.0:52531 (PUSH_CONNECT)	 control over tcp://0.0.0.0:52529 (PAIR_BIND)
           JINA@35809[E]:Since v0.3.6 jina uses uvloop to manage events and sockets, it often yields 20% speedupyou did not install uvloop. Try "pip install uvloop"
        encoder@35809[S]:ready and listening
  chunk_indexer@35810[I]:post initiating, this may take some time...
  chunk_indexer@35810[I]:post initiating, this may take some time takes 0.001 secs
  chunk_indexer@35810[S]:restore NumpyIndexer from /tmp/jina/southpark/sbnpsago/chunk_indexer-0/vecidx.bin
  chunk_indexer@35810[I]:post initiating, this may take some time...
  chunk_indexer@35810[I]:post initiating, this may take some time takes 0.000 secs
  chunk_indexer@35810[S]:restore BinaryPbIndexer from /tmp/jina/southpark/sbnpsago/chunk_indexer-0/chunkidx.bin
  chunk_indexer@35810[I]:post initiating, this may take some time...
  chunk_indexer@35810[I]:post initiating, this may take some time takes 0.001 secs
  chunk_indexer@35810[S]:successfully built CompoundIndexer from a yaml config
  chunk_indexer@35810[I]:loading index from /tmp/jina/southpark/sbnpsago/chunk_indexer-0/vec.gz...
  chunk_indexer@35810[I]:indexer size: 10001
  chunk_indexer@35810[I]:indexer size: 20002
  chunk_indexer@35810[I]:setting up sockets...
  chunk_indexer@35810[I]:input tcp://0.0.0.0:52531 (PULL_BIND) 	 output tcp://0.0.0.0:52535 (PUSH_CONNECT)	 control over tcp://0.0.0.0:52533 (PAIR_BIND)
           JINA@35810[E]:Since v0.3.6 jina uses uvloop to manage events and sockets, it often yields 20% speedupyou did not install uvloop. Try "pip install uvloop"
  chunk_indexer@35810[S]:ready and listening
         ranker@35811[I]:post initiating, this may take some time...
         ranker@35811[I]:post initiating, this may take some time takes 0.001 secs
         ranker@35811[S]:successfully built MinRanker from a yaml config
         ranker@35811[I]:setting up sockets...
         ranker@35811[I]:input tcp://0.0.0.0:52535 (PULL_BIND) 	 output tcp://0.0.0.0:52539 (PUSH_CONNECT)	 control over tcp://0.0.0.0:52537 (PAIR_BIND)
           JINA@35811[E]:Since v0.3.6 jina uses uvloop to manage events and sockets, it often yields 20% speedupyou did not install uvloop. Try "pip install uvloop"
         ranker@35811[S]:ready and listening
    doc_indexer@35812[I]:post initiating, this may take some time...
    doc_indexer@35812[I]:post initiating, this may take some time takes 0.000 secs
    doc_indexer@35812[S]:restore BinaryPbIndexer from /tmp/jina/southpark/sbnpsago/docIndexer.bin
    doc_indexer@35812[I]:setting up sockets...
    doc_indexer@35812[I]:input tcp://0.0.0.0:52539 (PULL_BIND) 	 output tcp://0.0.0.0:52540 (PUSH_BIND)	 control over tcp://0.0.0.0:52541 (PAIR_BIND)
           JINA@35812[E]:Since v0.3.6 jina uses uvloop to manage events and sockets, it often yields 20% speedupyou did not install uvloop. Try "pip install uvloop"
    doc_indexer@35812[S]:ready and listening
           JINA@35805[I]:using <class 'asyncio.unix_events._UnixSelectorEventLoop'> as event loop
E0826 12:52:07.713380000 4622511552 server_chttp2.cc:40]               {"created":"@1598435527.713123000","description":"No address added out of total 1 resolved","file":"src/core/ext/transport/chttp2/server/chttp2_server.cc","file_line":310,"referenced_errors":[{"created":"@1598435527.713099000","description":"Failed to add any wildcard listeners","file":"src/core/lib/iomgr/tcp_server_posix.cc","file_line":341,"referenced_errors":[{"created":"@1598435527.713050000","description":"Unable to configure socket","fd":102,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":215,"referenced_errors":[{"created":"@1598435527.713002000","description":"Address already in use","errno":48,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":188,"os_error":"Address already in use","syscall":"bind"}]},{"created":"@1598435527.713098000","description":"Unable to configure socket","fd":102,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":215,"referenced_errors":[{"created":"@1598435527.713088000","description":"Address already in use","errno":48,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":188,"os_error":"Address already in use","syscall":"bind"}]}]}]}
        gateway@35805[S]:gateway is listening at: 0.0.0.0:45678
           Flow@35805[I]:6 Pods (i.e. 6 Peas) are running in this Flow
           Flow@35805[S]:flow is now ready for use, current build_level is 1
please type a sentence: hello, dude
           JINA@35805[W]:parser Client can not recognize the following args: ['--read-only'], they are ignored. if you are using them from a global args (e.g. Flow), then please ignore this message
        gateway@35805[S]:connected to the gateway at 0.0.0.0:45678!
        gateway@35805[S]:terminated
    doc_indexer@35812[I]:received "control" from ctl▸⚐
    doc_indexer@35812[I]:RequestLoopEnd() causes the breaking from the event loop
    doc_indexer@35812[I]:#sent: 1 #recv: 1 sent_size: 294 Bytes recv_size: 251 Bytes
    doc_indexer@35812[I]:#sent: 1 #recv: 1 sent_size: 294 Bytes recv_size: 251 Bytes
         ranker@35811[I]:received "control" from ctl▸⚐
    doc_indexer@35812[I]:indexer size: 10001
    doc_indexer@35812[S]:terminated
         ranker@35811[I]:RequestLoopEnd() causes the breaking from the event loop
         ranker@35811[I]:#sent: 1 #recv: 1 sent_size: 289 Bytes recv_size: 251 Bytes
         ranker@35811[I]:#sent: 1 #recv: 1 sent_size: 289 Bytes recv_size: 251 Bytes
         ranker@35811[S]:terminated
  chunk_indexer@35810[I]:received "control" from ctl▸⚐
  chunk_indexer@35810[I]:RequestLoopEnd() causes the breaking from the event loop
  chunk_indexer@35810[I]:#sent: 1 #recv: 1 sent_size: 296 Bytes recv_size: 251 Bytes
  chunk_indexer@35810[I]:#sent: 1 #recv: 1 sent_size: 296 Bytes recv_size: 251 Bytes
  chunk_indexer@35810[I]:indexer size: 10001
  chunk_indexer@35810[I]:indexer size: 20002
  chunk_indexer@35810[S]:terminated
        encoder@35809[I]:received "control" from ctl▸⚐
        encoder@35809[I]:RequestLoopEnd() causes the breaking from the event loop
        encoder@35809[I]:#sent: 1 #recv: 1 sent_size: 290 Bytes recv_size: 251 Bytes
        encoder@35809[I]:#sent: 1 #recv: 1 sent_size: 290 Bytes recv_size: 251 Bytes
        encoder@35809[S]:terminated
       splittor@35808[I]:received "control" from ctl▸⚐
       splittor@35808[I]:RequestLoopEnd() causes the breaking from the event loop
           Flow@35805[S]:flow is closed and all resources should be released already, current build level is 0
Traceback (most recent call last):
       splittor@35808[I]:#sent: 1 #recv: 1 sent_size: 291 Bytes recv_size: 251 Bytes
  File "app.py", line 97, in <module>
    main()
  File "/Users/denysstetsenko/southpark-search/.venv/lib/python3.7/site-packages/click/core.py", line 829, in __call__
       splittor@35808[I]:#sent: 1 #recv: 1 sent_size: 291 Bytes recv_size: 251 Bytes
    return self.main(*args, **kwargs)
  File "/Users/denysstetsenko/southpark-search/.venv/lib/python3.7/site-packages/click/core.py", line 782, in main
       splittor@35808[S]:terminated
    rv = self.invoke(ctx)
  File "/Users/denysstetsenko/southpark-search/.venv/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/denysstetsenko/southpark-search/.venv/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "app.py", line 86, in main
    query(num_docs, top_k)
  File "app.py", line 57, in query
    f.search_lines(lines=[text, ], output_fn=ppr, top_k=top_k)
  File "/Users/denysstetsenko/southpark-search/.venv/lib/python3.7/site-packages/jina/flow/__init__.py", line 701, in search_lines
    self._get_client(**kwargs).search(input_lines(lines, filepath, size, sampling_rate, read_mode), output_fn)
  File "/Users/denysstetsenko/southpark-search/.venv/lib/python3.7/site-packages/jina/clients/python/__init__.py", line 210, in search
    self.dry_run(as_request='search')
  File "/Users/denysstetsenko/southpark-search/.venv/lib/python3.7/site-packages/jina/clients/python/__init__.py", line 187, in dry_run
    for resp in self._stub.Call(req_gen()):
  File "/Users/denysstetsenko/southpark-search/.venv/lib/python3.7/site-packages/grpc/_channel.py", line 416, in __next__
    return self._next()
  File "/Users/denysstetsenko/southpark-search/.venv/lib/python3.7/site-packages/grpc/_channel.py", line 706, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "{"created":"@1598435558.523339000","description":"Error received from peer ipv4:0.0.0.0:45678","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Socket closed","grpc_status":14}"


```

**Comment by denysthegitmenace** [comment]
After restarting the query service a number of times it started working fine. 
Not sure if this needs to be investigated further before closing.

**Comment by nan-wang** [comment]
hi, @denysthegitmenace Does this issue still persist? It looks like after typing the query sentences, jina was terminated right away.
