### ISSUE TITLE
cannot run southpark example

### ISSUE THREAD

**Issue by mingye-christina-wang** [jina-ai/examples#225]
I cloned the repo and installed the requirements for southpark-search (I have jina=0.5.5), but when I run `python app.py -t query` , I encounter this error:

Traceback (most recent call last):
  File "app.py", line 92, in <module>
    main()
  File "/Users/christina/anaconda3/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/christina/anaconda3/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/christina/anaconda3/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/christina/anaconda3/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "app.py", line 84, in main
    query(top_k)
  File "app.py", line 53, in query
    f.search_lines(lines=[text, ], output_fn=ppr, top_k=top_k)
  File "/Users/christina/anaconda3/lib/python3.7/site-packages/jina/flow/__init__.py", line 702, in search_lines
    **kwargs)
  File "/Users/christina/anaconda3/lib/python3.7/site-packages/jina/clients/python/__init__.py", line 203, in search
    self.dry_run(as_request='search')
  File "/Users/christina/anaconda3/lib/python3.7/site-packages/jina/clients/python/__init__.py", line 180, in dry_run
    for resp in self._stub.Call(req_gen()):
  File "/Users/christina/anaconda3/lib/python3.7/site-packages/grpc/_channel.py", line 416, in __next__
    return self._next()
  File "/Users/christina/anaconda3/lib/python3.7/site-packages/grpc/_channel.py", line 706, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.INTERNAL
	details = "Trying to connect an http1.x server"
	debug_error_string = "{"created":"@1600545377.125887000","description":"Error received from peer ipv4:0.0.0.0:45678","file":"src/core/lib/surface/call.cc","file_line":1055,"grpc_message":"Trying to connect an http1.x server","grpc_status":13}"

**Comment by maximilianwerk** [comment]
Have you run `python app.py -r index` beforehand? In case you are also joining the Hackaton, feel free to directly contact me in the slack. :)

**Comment by mingye-christina-wang** [comment]
I did not run that, but after running it, I still get the same error.
I'm doing another hackathon actually (HackMIT) :) but is there a way for me to access the Slack / some other way to contact you?

**Comment by maximilianwerk** [comment]
Solved in the chat. Another `python app.py -t query` was running in another terminal and blocked the port.
