### ISSUE TITLE
webqa-search example error with jina 0.6.8

### ISSUE THREAD

**Issue by yiouyou** [jina-ai/examples#255]
When run 'python app.py -t index' in webqa-search example with the latest jina 0.6.8, it shows error as below. Need help to fix the problem.

Appreciate your attention.
```
(py37-jina) sz@air:/mnt/d/coding/jina/examples/zh/webqa-search$ python app.py -t index
           Flow@10848[S]:successfully built Flow from a yaml config
    doc_indexer@10868[I]:post initiating, this may take some time...
    doc_indexer@10868[I]:post initiating, this may take some time takes 0 seconds (0.00s)
    doc_indexer@10868[S]:successfully built BinaryPbIndexer from a yaml config
    doc_indexer@10868[I]:setting up sockets...
    doc_indexer@10868[I]:input tcp://0.0.0.0:56119 (SUB_CONNECT)         output tcp://0.0.0.0:39993 (PUSH_CONNECT)     control over tcp://0.0.0.0:34407 (PAIR_BIND)
    doc_indexer@10868[S]:ready and listening
      extractor@10873[I]:post initiating, this may take some time...
      extractor@10873[I]:post initiating, this may take some time takes 0 seconds (0.00s)
      extractor@10873[S]:successfully built WebQATitleExtractor from a yaml config
      extractor@10873[I]:setting up sockets...
      extractor@10873[I]:input tcp://0.0.0.0:56119 (SUB_CONNECT)         output tcp://0.0.0.0:48757 (PUSH_CONNECT)     control over tcp://0.0.0.0:42221 (PAIR_BIND)
      extractor@10873[S]:ready and listening
        encoder@10878[I]:post initiating, this may take some time...
        encoder@10878[I]:post initiating, this may take some time takes 0 seconds (0.00s)
        encoder@10878[S]:successfully built BaseExecutor from a yaml config
        encoder@10878[I]:setting up sockets...
        encoder@10878[I]:input tcp://0.0.0.0:48757 (PULL_BIND)   output tcp://0.0.0.0:58321 (ROUTER_BIND)      control over tcp://0.0.0.0:35009 (PAIR_BIND)
        encoder@10878[S]:ready and listening
        encoder@10883[I]:post initiating, this may take some time...
        encoder@10883[I]:post initiating, this may take some time takes 0 seconds (0.00s)
        encoder@10883[S]:successfully built BaseExecutor from a yaml config
        encoder@10883[I]:setting up sockets...
        encoder@10883[I]:input tcp://0.0.0.0:47855 (PULL_BIND)   output tcp://0.0.0.0:40413 (PUSH_CONNECT)     control over tcp://0.0.0.0:34225 (PAIR_BIND)
        encoder@10883[S]:ready and listening
        encoder@10888[C]:unknown exception: ConstructorError(None, None, "could not determine a constructor for the tag '!TransformerRobertaEncoder'", <_ruamel_yaml.Mark object at 0x7fe8fb12c230>)
Traceback (most recent call last):
  File "/home/sz/py37-jina/lib/python3.7/site-packages/jina/peapods/pea.py", line 347, in run
    self.loop_body()
  File "/home/sz/py37-jina/lib/python3.7/site-packages/jina/peapods/pea.py", line 328, in loop_body
    self.load_executor()
  File "/home/sz/py37-jina/lib/python3.7/site-packages/jina/peapods/pea.py", line 199, in load_executor
    self.args.separated_workspace, self.args.replica_id)
  File "/home/sz/py37-jina/lib/python3.7/site-packages/jina/executors/__init__.py", line 431, in load_config
    return yaml.load(tmp_s)
  File "/home/sz/py37-jina/lib/python3.7/site-packages/ruamel/yaml/main.py", line 343, in load
    return constructor.get_single_data()
  File "/home/sz/py37-jina/lib/python3.7/site-packages/ruamel/yaml/constructor.py", line 113, in get_single_data
    return self.construct_document(node)
  File "/home/sz/py37-jina/lib/python3.7/site-packages/ruamel/yaml/constructor.py", line 118, in construct_document
    data = self.construct_object(node)
  File "/home/sz/py37-jina/lib/python3.7/site-packages/ruamel/yaml/constructor.py", line 146, in construct_object
    data = self.construct_non_recursive_object(node)
  File "/home/sz/py37-jina/lib/python3.7/site-packages/ruamel/yaml/constructor.py", line 181, in construct_non_recursive_object
    data = constructor(self, node)
  File "/home/sz/py37-jina/lib/python3.7/site-packages/ruamel/yaml/constructor.py", line 743, in construct_undefined
    node.start_mark,
ruamel.yaml.constructor.ConstructorError: could not determine a constructor for the tag '!TransformerRobertaEncoder'
  in "<unicode string>", line 1, column 1
        encoder@10888[S]:terminated
        encoder@10848[C]:fail to start <class 'jina.peapods.pea.BasePea'> with name encoder-1, this often means the executor used in the pod is not valid
Traceback (most recent call last):
  File "app.py", line 57, in <module>
    main()
  File "/home/sz/py37-jina/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/sz/py37-jina/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/sz/py37-jina/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sz/py37-jina/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "app.py", line 36, in main
    with flow:
  File "/home/sz/py37-jina/lib/python3.7/site-packages/jina/flow/__init__.py", line 444, in __enter__
    return self.start()
  File "/home/sz/py37-jina/lib/python3.7/site-packages/jina/flow/__init__.py", line 500, in start
    self.enter_context(v)
  File "/usr/lib/python3.7/contextlib.py", line 427, in enter_context
    result = _cm_type.__enter__(cm)
  File "/home/sz/py37-jina/lib/python3.7/site-packages/jina/peapods/pod.py", line 242, in __enter__
    return self.start()
  File "/home/sz/py37-jina/lib/python3.7/site-packages/jina/peapods/pod.py", line 376, in start
    return super().start()
  File "/home/sz/py37-jina/lib/python3.7/site-packages/jina/peapods/pod.py", line 212, in start
    self.enter_context(p)
  File "/usr/lib/python3.7/contextlib.py", line 427, in enter_context
    result = _cm_type.__enter__(cm)
  File "/home/sz/py37-jina/lib/python3.7/site-packages/jina/peapods/pea.py", line 424, in __enter__
    return self.start()
  File "/home/sz/py37-jina/lib/python3.7/site-packages/jina/peapods/pea.py", line 417, in start
    raise PeaFailToStart
jina.excepts.PeaFailToStart
```

**Comment by JoanFM** [comment]
Hello @yiouyou ,

Due to the speed of our development and the amount of examples we have in the repository, we are not supporting every example for every version. As you can see in the requirements, this needs `jina` version 0.3.8 and therefore it is not ready to be used with the most recent `0.6.8` version.

Many breaking changes have happened between these releases. 

Is there a special reason to have interest in this specific example and this version? We have other examples where we have kept  better adapted to newer versions.

Thanks

**Comment by JoanFM** [comment]
Hey @yiouyou , I close this issue as I realize u are trying to instantiate `!TransformerRobertaEncoder' which is not an encoder existing in our hub
