### ISSUE TITLE
x-as-service example error with jina 0.6.8

### ISSUE THREAD

**Issue by yiouyou** [jina-ai/examples#256]
When run 'python app.py' in x-as-service example with the latest jina 0.6.8, it shows error as below. Need help to fix the problem.

Appreciate your attention.
```
(py37-jina) sz@pc:/mnt/d/jina/examples/x-as-service$ python app.py
           spit@9130[I]:post initiating, this may take some time...
           spit@9130[I]:post initiating, this may take some time takes 0 seconds (0.00s)
           spit@9130[S]:successfully built Sentencizer from a yaml config
           spit@9130[I]:setting up sockets...
           spit@9130[I]:input tcp://0.0.0.0:60713 (PULL_BIND)    output tcp://0.0.0.0:34655 (PUSH_CONNECT)       control over tcp://0.0.0.0:42561 (PAIR_BIND)
           spit@9130[S]:ready and listening
         encode@9135[I]:post initiating, this may take some time...
         encode@9135[I]:post initiating, this may take some time takes 0 seconds (0.00s)
         encode@9135[S]:successfully built BaseExecutor from a yaml config
         encode@9135[I]:setting up sockets...
         encode@9135[I]:input tcp://0.0.0.0:34655 (PULL_BIND)    output tcp://0.0.0.0:57779 (ROUTER_BIND)        control over tcp://0.0.0.0:58929 (PAIR_BIND)
         encode@9135[S]:ready and listening
         encode@9140[I]:post initiating, this may take some time...
         encode@9140[I]:post initiating, this may take some time takes 0 seconds (0.00s)
         encode@9140[S]:successfully built BaseExecutor from a yaml config
         encode@9140[I]:setting up sockets...
         encode@9140[I]:input tcp://0.0.0.0:49929 (PULL_BIND)    output tcp://0.0.0.0:38427 (PUSH_BIND)  control over tcp://0.0.0.0:52495 (PAIR_BIND)
         encode@9140[S]:ready and listening
         encode@9145[I]:waiting ready signal from the container
         encode@9145[I]:usage: jina [-h] [-v] [-vf]
         encode@9145[I]:{hello-world, pod, flow, gateway ... 6 more choices} ...
         encode@9145[I]:jina: error: unrecognized arguments: --port-expose 51857
         encode@9145[S]:terminated
         encode@9111[C]:fail to start <class 'jina.peapods.container.ContainerPea'> with name encode-1, this often means the executor used in the pod is not valid
Traceback (most recent call last):
  File "app.py", line 29, in <module>
    with f:
  File "/home/sz/py37-jina/lib/python3.7/site-packages/jina/flow/__init__.py", line 444, in __enter__
    return self.start()
  File "/home/sz/py37-jina/lib/python3.7/site-packages/jina/flow/__init__.py", line 500, in start
    self.enter_context(v)
  File "/usr/lib/python3.7/contextlib.py", line 427, in enter_context
    result = _cm_type.__enter__(cm)
  File "/home/sz/py37-jina/lib/python3.7/site-packages/jina/peapods/pod.py", line 242, in __enter__
    return self.start()
  File "/home/sz/py37-jina/lib/python3.7/site-packages/jina/peapods/pod.py", line 376, in start
    return super().start()
  File "/home/sz/py37-jina/lib/python3.7/site-packages/jina/peapods/pod.py", line 212, in start
    self.enter_context(p)
  File "/usr/lib/python3.7/contextlib.py", line 427, in enter_context
    result = _cm_type.__enter__(cm)
  File "/home/sz/py37-jina/lib/python3.7/site-packages/jina/peapods/pea.py", line 424, in __enter__
    return self.start()
  File "/home/sz/py37-jina/lib/python3.7/site-packages/jina/peapods/pea.py", line 417, in start
    raise PeaFailToStart
jina.excepts.PeaFailToStart
```

**Comment by JoanFM** [comment]
Hello @yiouyou 

As per the `webqa-search` example:

Due to the speed of our development and the amount of examples we have in the repository, we are not supporting every example for every version. As you can see in the requirements, this needs jina version 0.4.1 and therefore it is not ready to be used with the most recent 0.6.8 version.

Many breaking changes have happened between these releases.

Is there a special reason to have interest in this specific example and this version? We have other examples where we have kept better adapted to newer versions.

Thanks

**Comment by yiouyou** [comment]
@JoanFM which example does adapt newer version better? I'd like to try. After learning, maybe I can find a way to fix those breaking changes.

**Comment by JoanFM** [comment]
Hey @yiouyou,

You can try southpark example, multilyrics search, cross-modal search or object search.

**Comment by alexcg1** [comment]
Just a quick follow-up here: `x-as-service` has been moved to our [legacy-examples repo](https://github.com/jina-ai/legacy-examples/tree/main/x-as-service) and is no longer maintained. I'll close this issue.
