### ISSUE TITLE
Error installing dependencies of fashion-example-query module (uvloop does not support Windows at the moment)

### ISSUE THREAD

**Issue by ManudattaG** [jina-ai/examples#283]
Error installing dependencies from requirements.txt of fashion-example-query module.

```
$ pip install -r requirements.txt
Collecting jina[devel,tensorflow,torch,transformers]==0.6.4
  Using cached jina-0.6.4.tar.gz (217 kB)
Collecting lz4
  Using cached lz4-3.1.0-cp38-cp38-win32.whl (144 kB)
Collecting uvloop
  Using cached uvloop-0.14.0.tar.gz (2.0 MB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\<username>\appdata\local\programs\python\python38-32\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\<username>\\AppData\\Local\\Temp\\pip-install-hy528gd7\\uvloop\\setup.py'"'"'; __file__='"'"'C:\\Users\\<username>\\AppData\\Local\\Temp\\pip-install-hy528gd7\\uvloop\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\<username>\AppData\Local\Temp\pip-pip-egg-info-3nvv76vg'
         cwd: C:\Users\<username>\AppData\Local\Temp\pip-install-hy528gd7\uvloop\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\<username>\AppData\Local\Temp\pip-install-hy528gd7\uvloop\setup.py", line 15, in <module>
        raise RuntimeError('uvloop does not support Windows at the moment')
    RuntimeError: uvloop does not support Windows at the moment
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Please help me out to resolve this. Thanks.

**Comment by JoanFM** [comment]
Hello @ManudattaG ,

Unfortunately, we do not natively support Windows, please see the issue https://github.com/jina-ai/jina/issues/1252.

You can use `Windows Subsystem for Linux` (WSL). We are planning to add documentation on how to do that.

I hope this helps.
