### ISSUE TITLE
Fix pokedex with Python 3.8

### ISSUE THREAD

**Issue by cristianmtr** [jina-ai/examples#400]
Currently cannot find combination of Python 3.8 with TF and Jina that works for Pokedex

Stack traces:

```
Traceback (most recent call last): 
  File "/home/cristian/envs/tum/lib/python3.8/site-packages/jina/peapods/runtimes/zmq/zed.py", line 159, in _msg_callback
    self._zmqlet.send_message(self._callback(msg))
  File "/home/cristian/envs/tum/lib/python3.8/site-packages/jina/peapods/runtimes/zmq/zed.py", line 148, in _callback
    self._pre_hook(msg)._handle(msg)._post_hook(msg)
  File "/home/cristian/envs/tum/lib/python3.8/site-packages/jina/peapods/runtimes/zmq/zed.py", line 141, in _handle
    self._executor(self.request_type)
  File "/home/cristian/envs/tum/lib/python3.8/site-packages/jina/executors/__init__.py", line 433, in __call__
    d()
  File "/home/cristian/envs/tum/lib/python3.8/site-packages/jina/drivers/__init__.py", line 335, in __call__
    self._apply_all(self.docs, *args, **kwargs)
  File "/home/cristian/envs/tum/lib/python3.8/site-packages/jina/drivers/encode.py", line 29, in _apply_all
    embeds = self.exec_fn(contents)
  File "/home/cristian/envs/tum/lib/python3.8/site-packages/jina/executors/decorators.py", line 245, in arg_wrapper
    return func(*args, **kwargs)
  File "/home/cristian/envs/tum/lib/python3.8/site-packages/jina/executors/decorators.py", line 87, in arg_wrapper
    r = func(self, *args, **kwargs)
  File "/home/cristian/envs/tum/lib/python3.8/site-packages/jina/hub/encoders/image/BigTransferEncoder/__init__.py", line 73, in encode
    _output = self.model(self._get_input(data.astype(np.float32)))
  File "/home/cristian/envs/tum/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1605, in __call__
    return self._call_impl(args, kwargs)
  File "/home/cristian/envs/tum/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1645, in _call_impl
    return self._call_flat(args, self.captured_inputs, cancellation_manager)
  File "/home/cristian/envs/tum/lib/python3.8/site-packages/tensorflow/python/saved_model/load.py", line 100, in _call_flat
    return super(_WrapperFunction, self)._call_flat(args, captured_inputs,
  File "/home/cristian/envs/tum/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1745, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "/home/cristian/envs/tum/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 593, in call
    outputs = execute.execute(
  File "/home/cristian/envs/tum/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.FailedPreconditionError:  Error while reading resource variable resnet/block4/unit01/a/proj/stand
ardized_conv2d/kernel_51699 from Container: localhost. This could mean that the variable was uninitialized. Not found: Resource localhost
/resnet/block4/unit01/a/proj/standardized_conv2d/kernel_51699/N10tensorflow3VarE does not exist.
         [[{{node StatefulPartitionedCall/resnet/block4/unit01/a/proj/standardized_conv2d/ReadVariableOp}}]] [Op:__inference_signature_wr
apper_4112]

Function call stack:
signature_wrapper

```

**Comment by jakob1111996** [comment]
This seems to be a tensorflow issue.
If you replace these two lines in the BigTransferEncoder:
`import tensorflow as tf`
`_model = tf.saved_model.load(self.model_path)`
with these:
`from tensorflow.python.keras.models import load_model`
`_model = load_model(self.model_path)`
then everything works fine.
I will fix this when pushing the example to Jina release 2.0.
