### ISSUE TITLE
southpark-search: Exception iterating requests

### ISSUE THREAD

**Issue by alexcg1** [jina-ai/examples#51]
# Environment

* Clean Focal Fossa install
* Tested on two branches:
  - `master`
  - `fix-broken-flow-in-linux-49`

# Reproduce

`python app.py -t index -n 100000`

# Output

```
           Flow@32924[S]:[32msuccessfully built Flow from a yaml config[0m
     dispatcher@32933[I]:[37mpost initiating, this may take some time...[0m
     dispatcher@32933[I]:[37mpost initiating, this may take some time takes 0.000 secs[0m
     dispatcher@32933[S]:[32msuccessfully built BaseExecutor from a yaml config[0m
     dispatcher@32933[I]:[37msetting up sockets...[0m
     dispatcher@32933[I]:[37minput [33mtcp://0.0.0.0:53089[0m (PULL_BIND) 	 output [33mtcp://0.0.0.0:54667[0m (PUB_BIND)	 control over [33mtcp://0.0.0.0:52269[0m (PAIR_BIND)[0m
     dispatcher@32933[S]:[32mready and listening[0m
       splittor@32936[W]:[40m[33mthe min_sent_len (=2) should be smaller or equal to the max_sent_len (=64)[0m
       splittor@32936[I]:[37mpost initiating, this may take some time...[0m
       splittor@32936[I]:[37mpost initiating, this may take some time takes 0.000 secs[0m
       splittor@32936[S]:[32msuccessfully built Sentencizer from a yaml config[0m
       splittor@32936[I]:[37msetting up sockets...[0m
       splittor@32936[I]:[37minput [33mtcp://0.0.0.0:54667[0m (SUB_CONNECT) 	 output [33mtcp://0.0.0.0:47697[0m (PUSH_CONNECT)	 control over [33mtcp://0.0.0.0:54221[0m (PAIR_BIND)[0m
       splittor@32936[S]:[32mready and listening[0m
        encoder@32939[I]:[37mpost initiating, this may take some time...[0m
        encoder@32939[I]:[37mpost initiating, this may take some time takes 1.769 secs[0m
        encoder@32939[S]:[32msuccessfully built TransformerTorchEncoder from a yaml config[0m
        encoder@32939[I]:[37msetting up sockets...[0m
        encoder@32939[I]:[37minput [33mtcp://0.0.0.0:47697[0m (PULL_BIND) 	 output [33mtcp://0.0.0.0:41123[0m (PUSH_CONNECT)	 control over [33mtcp://0.0.0.0:43255[0m (PAIR_BIND)[0m
        encoder@32939[S]:[32mready and listening[0m
  chunk_indexer@32942[I]:[37mpost initiating, this may take some time...[0m
  chunk_indexer@32942[I]:[37mpost initiating, this may take some time takes 0.000 secs[0m
  chunk_indexer@32942[S]:[32msuccessfully built NumpyIndexer from a yaml config[0m
  chunk_indexer@32942[I]:[37mpost initiating, this may take some time...[0m
  chunk_indexer@32942[I]:[37mpost initiating, this may take some time takes 0.000 secs[0m
  chunk_indexer@32942[S]:[32msuccessfully built BasePbIndexer from a yaml config[0m
  chunk_indexer@32942[I]:[37mpost initiating, this may take some time...[0m
  chunk_indexer@32942[I]:[37mpost initiating, this may take some time takes 0.000 secs[0m
  chunk_indexer@32942[S]:[32msuccessfully built ChunkIndexer from a yaml config[0m
  chunk_indexer@32942[W]:[40m[33myou can not query from <jina.executors.indexers.vector.numpy.NumpyIndexer object at 0x7f9e657a65b0> as its "query_handler" is not set. If you are indexing data from scratch then it is fine. If you are querying data then the index file must be empty or broken.[0m
  chunk_indexer@32942[I]:[37msetting up sockets...[0m
  chunk_indexer@32942[I]:[37minput [33mtcp://0.0.0.0:41123[0m (PULL_BIND) 	 output [33mtcp://0.0.0.0:53169[0m (PUSH_CONNECT)	 control over [33mtcp://0.0.0.0:34031[0m (PAIR_BIND)[0m
  chunk_indexer@32942[S]:[32mready and listening[0m
    doc_indexer@32945[I]:[37mpost initiating, this may take some time...[0m
    doc_indexer@32945[I]:[37mpost initiating, this may take some time takes 0.000 secs[0m
    doc_indexer@32945[S]:[32msuccessfully built DocPbIndexer from a yaml config[0m
    doc_indexer@32945[I]:[37msetting up sockets...[0m
    doc_indexer@32945[I]:[37minput [33mtcp://0.0.0.0:54667[0m (SUB_CONNECT) 	 output [33mtcp://0.0.0.0:53169[0m (PUSH_CONNECT)	 control over [33mtcp://0.0.0.0:57293[0m (PAIR_BIND)[0m
    doc_indexer@32945[S]:[32mready and listening[0m
       join_all@32948[I]:[37mpost initiating, this may take some time...[0m
       join_all@32948[I]:[37mpost initiating, this may take some time takes 0.000 secs[0m
       join_all@32948[S]:[32msuccessfully built BaseExecutor from a yaml config[0m
       join_all@32948[I]:[37msetting up sockets...[0m
       join_all@32948[I]:[37minput [33mtcp://0.0.0.0:53169[0m (PULL_BIND) 	 output [33mtcp://0.0.0.0:34151[0m (PUSH_BIND)	 control over [33mtcp://0.0.0.0:42943[0m (PAIR_BIND)[0m
       join_all@32948[S]:[32mready and listening[0m
       join_all@32924[I]:[37mpost initiating, this may take some time...[0m
       join_all@32924[I]:[37mpost initiating, this may take some time takes 0.001 secs[0m
       join_all@32924[S]:[32mgateway is listening at: 0.0.0.0:55767[0m
           Flow@32924[I]:[37m7 Pods (i.e. 7 Peas) are running in this Flow[0m
           Flow@32924[S]:[32mflow is now ready for use, current build_level is GRAPH[0m
           JINA@32924[W]:[40m[33m"raw_bytes" is deprecated in "index()" and will be removed in the next version; please use "input_fn" instead[0m
       join_all@32924[S]:[32mconnected to the gateway at 0.0.0.0:55767![0m

[36mindex[0m [[32m=[0m                   ] 📃      0 ⏱️ 0.0s 🐎 0.0/s      0 batchindex ...	file not found: /tmp/jina/southpark/character-lines.csv
[32m    [0.001 secs][0m
	[32m✅ done in ⏱ 0.0s 🐎 0.0/s[0m
       join_all@32924[I]:[37msetting up sockets...[0m
       join_all@32924[I]:[37minput [33mtcp://0.0.0.0:34151[0m (PULL_CONNECT) 	 output [33mtcp://0.0.0.0:53089[0m (PUSH_CONNECT)	 control over [33mipc:///tmp/tmpzl6dj5e7[0m (PAIR_BIND)[0m
       join_all@32924[I]:[37mprefetching 50 requests...[0m
       join_all@32924[W]:[40m[33mif this takes too long, you may want to take smaller "--prefetch" or ask client to reduce "--batch-size"[0m
       join_all@32924[I]:[37mprefetching 50 requests takes 0.000 secs[0m
       join_all@32924[I]:[37m#sent: 0 #recv: 0 sent_size: 0 Bytes recv_size: 0 Bytes[0m
       join_all@32924[S]:[32mterminated[0m
       join_all@32924[S]:[32mterminated[0m
       join_all@32948[I]:[37mreceived "control" from ctl[32m▸[0m⚐[0m
       join_all@32948[I]:[37mbreak from the event loop[0m
       join_all@32948[I]:[37m#sent: 0 #recv: 1 sent_size: 0 Bytes recv_size: 249 Bytes[0m
       join_all@32948[I]:[37m#sent: 1 #recv: 1 sent_size: 289 Bytes recv_size: 249 Bytes[0m
       join_all@32948[S]:[32mterminated[0m
    doc_indexer@32945[I]:[37mreceived "control" from ctl[32m▸[0m⚐[0m
    doc_indexer@32945[I]:[37mbreak from the event loop[0m
    doc_indexer@32945[I]:[37mno update since 2020-05-17 14:29:50, will not save. If you really want to save it, call "touch()" before "save()" to force saving[0m
    doc_indexer@32945[I]:[37mexecutor says there is nothing to save[0m
    doc_indexer@32945[I]:[37m#sent: 0 #recv: 1 sent_size: 0 Bytes recv_size: 249 Bytes[0m
    doc_indexer@32945[I]:[37m#sent: 1 #recv: 1 sent_size: 292 Bytes recv_size: 249 Bytes[0m
    doc_indexer@32945[S]:[32mterminated[0m
  chunk_indexer@32942[I]:[37mreceived "control" from ctl[32m▸[0m⚐[0m
  chunk_indexer@32942[I]:[37mbreak from the event loop[0m
  chunk_indexer@32942[I]:[37mno update since 2020-05-17 14:29:50, will not save. If you really want to save it, call "touch()" before "save()" to force saving[0m
  chunk_indexer@32942[I]:[37mno update since 2020-05-17 14:29:50, will not save. If you really want to save it, call "touch()" before "save()" to force saving[0m
  chunk_indexer@32942[I]:[37mno update since 2020-05-17 14:29:50, will not save. If you really want to save it, call "touch()" before "save()" to force saving[0m
  chunk_indexer@32942[I]:[37mdumped changes to the executor,   0s since last the save[0m
  chunk_indexer@32942[I]:[37m#sent: 0 #recv: 1 sent_size: 0 Bytes recv_size: 249 Bytes[0m
  chunk_indexer@32942[I]:[37m#sent: 1 #recv: 1 sent_size: 294 Bytes recv_size: 249 Bytes[0m
  chunk_indexer@32942[S]:[32mterminated[0m
        encoder@32939[I]:[37mreceived "control" from ctl[32m▸[0m⚐[0m
        encoder@32939[I]:[37mbreak from the event loop[0m
        encoder@32939[I]:[37m#sent: 0 #recv: 1 sent_size: 0 Bytes recv_size: 249 Bytes[0m
        encoder@32939[I]:[37m#sent: 1 #recv: 1 sent_size: 288 Bytes recv_size: 249 Bytes[0m
        encoder@32939[S]:[32mterminated[0m
       splittor@32936[I]:[37mreceived "control" from ctl[32m▸[0m⚐[0m
       splittor@32936[I]:[37mbreak from the event loop[0m
       splittor@32936[I]:[37m#sent: 0 #recv: 1 sent_size: 0 Bytes recv_size: 249 Bytes[0m
       splittor@32936[I]:[37m#sent: 1 #recv: 1 sent_size: 289 Bytes recv_size: 249 Bytes[0m
       splittor@32936[S]:[32mterminated[0m
     dispatcher@32933[I]:[37mreceived "control" from ctl[32m▸[0m⚐[0m
     dispatcher@32933[I]:[37mbreak from the event loop[0m
     dispatcher@32933[I]:[37m#sent: 0 #recv: 1 sent_size: 0 Bytes recv_size: 249 Bytes[0m
     dispatcher@32933[I]:[37m#sent: 1 #recv: 1 sent_size: 291 Bytes recv_size: 249 Bytes[0m
     dispatcher@32933[S]:[32mterminated[0m
           Flow@32924[S]:[32mflow is closed and all resources should be released already, current build level is EMPTY[0m
Traceback (most recent call last):
  File "/home/alexcg/.local/lib/python3.8/site-packages/jina/clients/python/grpc.py", line 71, in start
    self.call(*args, **kwargs)
  File "/home/alexcg/.local/lib/python3.8/site-packages/jina/clients/python/__init__.py", line 121, in call
    for resp in self._stub.Call(req_iter):
  File "/home/alexcg/.local/lib/python3.8/site-packages/grpc/_channel.py", line 416, in __next__
    return self._next()
  File "/home/alexcg/.local/lib/python3.8/site-packages/grpc/_channel.py", line 689, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception iterating requests!"
	debug_error_string = "None"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app.py", line 82, in <module>
    main()
  File "/home/alexcg/.local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/alexcg/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/alexcg/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/alexcg/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "app.py", line 65, in main
    fl.index(raw_bytes=read_data(data_path, num_docs), batch_size=8)
  File "/home/alexcg/.local/lib/python3.8/site-packages/jina/helper.py", line 31, in wrapper
    return f(*args, **kwargs)
  File "/home/alexcg/.local/lib/python3.8/site-packages/jina/flow/__init__.py", line 606, in index
    self._get_client(**kwargs).index(input_fn, output_fn)
  File "/home/alexcg/.local/lib/python3.8/site-packages/jina/clients/python/__init__.py", line 184, in index
    self.start(output_fn, **kwargs)
  File "/home/alexcg/.local/lib/python3.8/site-packages/jina/clients/python/grpc.py", line 82, in start
    raise BadClient('%s error in grpc: %s '
jina.excepts.BadClient: StatusCode.UNKNOWN error in grpc: Exception iterating requests! often the case is that you define/send a bad input iterator to jina, please double check your input iterator
```

**Comment by alexcg1** [comment]
Also had same error on my Manjaro install

**Comment by nan-wang** [comment]
hi, @alexcg1 I notice this in the logs,

```
file not found: /tmp/jina/southpark/character-lines.csv
```

Have you ran `bash ./get_data.sh` before?

**Comment by alexcg1** [comment]
Ha. My bad! I'd run it before but done a reboot since. Since it only downloads  to /tmp it got wiped. Still having problems though, just not this one this issue addresses

**Comment by iedmrc** [comment]
How did you solve this issue? I'm also having the same but with my own data and using https://github.com/jina-ai/examples/blob/master/southpark-search/README.restful.md#index-your-own-data

**Comment by alexcg1** [comment]
I ran `./get_data.sh` again in my case. But I'm not sure that's happening for you, since I'm assuming your data is in a stable location, not `/tmp`. I'd suggest opening a new issue.
