### ISSUE TITLE
[UrbanDict] ruamel.yaml.constructor.ConstructorError: could not determine a constructor for the tag '!DocKVIndexDriver'

### ISSUE THREAD

**Issue by xubiuit** [jina-ai/examples#74]
Hi guys,

I am trying to setup the UrbanDict example.
Instead using index 10000, I just used 100 (since I just want to test a bit, and check out the process only).
But I faced this when running `python app.py -t index -n 100`.
Env: `python3.8`, `jina-0.2.8`

```python
chunk_indexer@6939[I]:input tcp://0.0.0.0:51377 (PULL_BIND) 	 output tcp://0.0.0.0:51385 (PUSH_CONNECT)	 control over tcp://0.0.0.0:51379 (PAIR_BIND)
  chunk_indexer@6939[S]:ready and listening
    doc_indexer@6940[C]:unknown exception: ConstructorError(None, None, "could not determine a constructor for the tag '!DocKVIndexDriver'", <_ruamel_yaml.Mark object at 0x10f9ea770>)
Traceback (most recent call last):
  File "/Users/binhnguyen/env/jina-python3-env/lib/python3.8/site-packages/jina/peapods/pea.py", line 343, in run
    self.loop_body()
  File "/Users/binhnguyen/env/jina-python3-env/lib/python3.8/site-packages/jina/peapods/pea.py", line 305, in loop_body
    self.load_executor()
  File "/Users/binhnguyen/env/jina-python3-env/lib/python3.8/site-packages/jina/peapods/pea.py", line 198, in load_executor
    self.executor = BaseExecutor.load_config(self.args.yaml_path,
  File "/Users/binhnguyen/env/jina-python3-env/lib/python3.8/site-packages/jina/executors/__init__.py", line 404, in load_config
    return yaml.load(tmp_s)
  File "/Users/binhnguyen/env/jina-python3-env/lib/python3.8/site-packages/ruamel/yaml/main.py", line 343, in load
    return constructor.get_single_data()
  File "/Users/binhnguyen/env/jina-python3-env/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 113, in get_single_data
    return self.construct_document(node)
  File "/Users/binhnguyen/env/jina-python3-env/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 118, in construct_document
    data = self.construct_object(node)
  File "/Users/binhnguyen/env/jina-python3-env/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 146, in construct_object
    data = self.construct_non_recursive_object(node)
  File "/Users/binhnguyen/env/jina-python3-env/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 181, in construct_non_recursive_object
    data = constructor(self, node)
  File "/Users/binhnguyen/env/jina-python3-env/lib/python3.8/site-packages/jina/executors/__init__.py", line 445, in from_yaml
    return cls._get_instance_from_yaml(constructor, node)[0]
  File "/Users/binhnguyen/env/jina-python3-env/lib/python3.8/site-packages/jina/executors/__init__.py", line 449, in _get_instance_from_yaml
    data = ruamel.yaml.constructor.SafeConstructor.construct_mapping(
  File "/Users/binhnguyen/env/jina-python3-env/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 440, in construct_mapping
    return BaseConstructor.construct_mapping(self, node, deep=deep)
  File "/Users/binhnguyen/env/jina-python3-env/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 255, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/Users/binhnguyen/env/jina-python3-env/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 146, in construct_object
    data = self.construct_non_recursive_object(node)
  File "/Users/binhnguyen/env/jina-python3-env/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 188, in construct_non_recursive_object
    for _dummy in generator:
  File "/Users/binhnguyen/env/jina-python3-env/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 723, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/Users/binhnguyen/env/jina-python3-env/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 440, in construct_mapping
    return BaseConstructor.construct_mapping(self, node, deep=deep)
  File "/Users/binhnguyen/env/jina-python3-env/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 255, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/Users/binhnguyen/env/jina-python3-env/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 146, in construct_object
    data = self.construct_non_recursive_object(node)
  File "/Users/binhnguyen/env/jina-python3-env/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 188, in construct_non_recursive_object
    for _dummy in generator:
  File "/Users/binhnguyen/env/jina-python3-env/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 723, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/Users/binhnguyen/env/jina-python3-env/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 440, in construct_mapping
    return BaseConstructor.construct_mapping(self, node, deep=deep)
  File "/Users/binhnguyen/env/jina-python3-env/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 255, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/Users/binhnguyen/env/jina-python3-env/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 146, in construct_object
    data = self.construct_non_recursive_object(node)
  File "/Users/binhnguyen/env/jina-python3-env/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 188, in construct_non_recursive_object
    for _dummy in generator:
  File "/Users/binhnguyen/env/jina-python3-env/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 717, in construct_yaml_seq
    data.extend(self.construct_sequence(node))
  File "/Users/binhnguyen/env/jina-python3-env/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 211, in construct_sequence
    return [self.construct_object(child, deep=deep) for child in node.value]
  File "/Users/binhnguyen/env/jina-python3-env/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 211, in <listcomp>
    return [self.construct_object(child, deep=deep) for child in node.value]
  File "/Users/binhnguyen/env/jina-python3-env/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 146, in construct_object
    data = self.construct_non_recursive_object(node)
  File "/Users/binhnguyen/env/jina-python3-env/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 181, in construct_non_recursive_object
    data = constructor(self, node)
  File "/Users/binhnguyen/env/jina-python3-env/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 739, in construct_undefined
    raise ConstructorError(
ruamel.yaml.constructor.ConstructorError: could not determine a constructor for the tag '!DocKVIndexDriver'
  in "<unicode string>", line 22, column 7
    doc_indexer@6940[S]:terminated
    doc_indexer@6932[C]:fail to start <class 'jina.peapods.pea.BasePea'> with name doc_indexer
       join_all@6941[I]:post initiating, this may take some time...```

**Comment by xubiuit** [comment]
then I stucked here around 20 mins

```python
  chunk_indexer@7685[I]:received "index" from gateway▸splittor▸encoder▸⚐
       splittor@7681[W]:doc 90 gives no chunk
       splittor@7681[W]:doc 91 gives no chunk
  chunk_indexer@7685[W]:these docs contain no chunk: [64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79]
       splittor@7681[W]:doc 92 gives no chunk
       splittor@7681[W]:doc 93 gives no chunk
       splittor@7681[W]:doc 94 gives no chunk
       splittor@7681[W]:doc 95 gives no chunk
       splittor@7681[I]:received "index" from gateway▸⚐
       join_all@7687[I]:received "index" from gateway▸splittor▸encoder▸chunk_indexer▸⚐
       splittor@7681[W]:doc 96 gives no chunk
       splittor@7681[W]:doc 97 gives no chunk
        encoder@7682[I]:received "index" from gateway▸splittor▸⚐
       join_all@7687[I]:collected 1/2 parts of IndexRequest
       splittor@7681[W]:doc 98 gives no chunk
       splittor@7681[W]:doc 99 gives no chunk
        encoder@7682[W]:these docs contain no chunk: [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95]
        encoder@7682[I]:received "index" from gateway▸splittor▸⚐
  chunk_indexer@7685[I]:received "index" from gateway▸splittor▸encoder▸⚐
        encoder@7682[W]:these docs contain no chunk: [96, 97, 98, 99]
  chunk_indexer@7685[W]:these docs contain no chunk: [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95]
  chunk_indexer@7685[I]:received "index" from gateway▸splittor▸encoder▸⚐
  chunk_indexer@7685[W]:these docs contain no chunk: [96, 97, 98, 99]
       join_all@7687[I]:received "index" from gateway▸splittor▸encoder▸chunk_indexer▸⚐
       join_all@7687[I]:collected 1/2 parts of IndexRequest
       join_all@7687[I]:received "index" from gateway▸splittor▸encoder▸chunk_indexer▸⚐
       join_all@7687[I]:collected 1/2 parts of IndexRequest
```

**Comment by xubiuit** [comment]
I've checkout release`jina 0.2.1` and use `python3.7`. Everything seems okay now.
I think you guys should take a look on newest release and figure out the reason why.

**Comment by gsajko** [comment]
I'm also having this issue.
Env: `python3.8`, `jina-0.3.0`

**Comment by nan-wang** [comment]
@xubiuit and @gsajko We've just fixed urbandict example. Would you please give it another try? Sorry for the trouble, we were short of hands to make every example up to date.

**Comment by xubiuit** [comment]
@nan-wang can you give us the stable version which you've just fixed? e.g: python version, jina version, example version?
Thanks so much!

**Comment by gsajko** [comment]
For me indexer works:
`python3.8`, `jina-0.3.3`

not sure if I needed to updated jina. Indexing works. But at query:

`python app.py -t query`

`
           JINA@12098[W]:parser Flow can not recognize the following args: ['--read-only', '--port-grpc', '45678'], they are ignored. if you are using them from a global args (e.g. Flow), then please ignore this message`

And when I enter word when prompted:

`python3.8/site-packages/jina/clients/python/grpc.py", line 83, in start
    raise BadClient('%s error in grpc: %s '
jina.excepts.BadClient: StatusCode.UNKNOWN error in grpc: Exception iterating requests! often the case is that you define/send a bad input iterator to jina, please double check your input iterator`

**Comment by howardwang15** [comment]
I pulled from the repo again and now it works

**Comment by tagizaade** [comment]
I have the same problem:

python 3.7
jina 0.3.7

ruamel.yaml.constructor.ConstructorError: could not determine a constructor for the tag '!DocKVIndexDriver'

**Comment by JoanFM** [comment]
Hello @tagizaade,

Have you tried getting the latest version of the examples repo as @howardwang15 suggested?

**Comment by tagizaade** [comment]
Hi
Sorry I didn't know that ReadMe is not updated.
Yes I used the source files in repository instead of using configs outlined in ReadMe and it's ok right now.
